### ISSUE TITLE
no reference to other ontologies

### ISSUE THREAD

**Issue by flyon** [SemanGit/SemanGit#22]
Hey, I was looking for an ontology for data on github. Great project! 
We will be live converting data from the gibhub graphql endpoint to Linked Data, possibly using this ontology.

I noticed you're not using any references to other terms in other ontologies. For example this ontology introduces its own generic `:user` Class, whilst there are already some well defined classes like `foaf:OnlineAccount` or `sioc:UserAccount`.

Was this intentional?

Would you be open to pull requests that would introduce some `rdfs:subClassOf` relations?

**Comment by maboeckmann** [comment]
Dear @flyon,

thank you for your request! We are happy to hear that our work might be useful to you. The missing relations to foaf and other ontologies are not intentional and were caused by our lack of experience with ontologies back then.

We would be very happy to see this work continued to make it follow more standards and be more useful to others. Please feel free to create pull requests that generally improve the quality/reusability of the ontology or that extend it in a sensible way.
